/**
 * Single source of truth for every word and media path on the site.
 *
 * PLACEHOLDER CONTENT — READ BEFORE PUBLISHING
 * --------------------------------------------
 * PRODUCT.md records that finished case studies exist but none are in this
 * repository. Nothing here claims a client, an employer, a testimonial, an
 * award or a metric, because none has been confirmed. The project entries are
 * empty slots shaped like real ones so the layout can be built and reviewed;
 * replace `title`, `discipline`, `year`, `summary` and the media paths with
 * real work before this goes live. Deleting a slot is fine — the grid adapts.
 */

export const site = {
  name: "Zahrah",
  role: "Photographer, videographer & designer",
  // TODO: confirm domain before launch; used for canonical URLs and OG tags.
  url: "https://example.com",
  email: "zahrah.omer1@gmail.com",
  /**
   * Supplied as 03002773339 and read as Pakistan (+92). wa.me needs digits
   * only, no plus, no spaces. Correct the country code here if that is wrong —
   * a wrong code fails silently as a dead link.
   */
  whatsapp: "923002773339",
  whatsappDisplay: "+92 300 277 3339",
} as const;

/** Preloader rotation. Order matters — it reads as a sentence being rewritten. */
export const professions = [
  "videographer",
  "photographer",
  "designer",
  "creative director",
  "brand builder",
] as const;

export const hero = {
  /**
   * Drop real footage at public/media/hero.webm (and/or .mp4 — both are wired).
   * Until then the poster still is used with a slow drift, which is why the
   * section does not look broken without it.
   */
  video: "/media/hero.webm",
  videoMp4: "/media/hero.mp4",
  poster: "/media/hero-poster.png",
  headline: ["Pictures that", "hold their nerve"],
  intro:
    "Hey, I\u2019m Zahrah. I shoot, cut and design \u2014 photography, film, identity and the sites they live on. Based in Pakistan, working wherever the project is.",
  scrollCue: "Scroll to explore",
} as const;

export const about = {
  heading: "I make work that earns a second look.",
  body: [
    "I move between a camera, a timeline and a typeface, and I have stopped pretending those are separate jobs. A brand that photographs badly was designed badly. A film that cuts well was storyboarded like a layout.",
    "The through-line is authorship: deciding what a thing is before deciding what it looks like, then holding that decision through every frame, spread and screen.",
  ],
} as const;

export type Project = {
  slug: string;
  title: string;
  discipline: string;
  year: string;
  summary: string;
  /** Poster image. Falls back to a typographic placeholder when missing. */
  image?: string;
  /** Optional muted loop revealed on hover. None exist yet. */
  preview?: string;
  /** Grid weight. "wide" spans the full column set, "tall" doubles height. */
  scale?: "wide" | "tall" | "standard";
};

export const projects: Project[] = [
  {
    slug: "portrait-series",
    title: "Portrait Series",
    discipline: "Photography",
    year: "—",
    summary:
      "Placeholder slot. Replace with a real series: what you were after, what you changed on the day, what the client did with it.",
    image: "/media/work-01.png",
    scale: "wide",
  },
  {
    slug: "short-film",
    title: "Short Film",
    discipline: "Videography",
    year: "—",
    summary: "Placeholder slot. Replace with a real film and its brief.",
    image: "/media/work-02.png",
    scale: "tall",
  },
  {
    slug: "identity-system",
    title: "Identity System",
    discipline: "Brand & graphic design",
    year: "—",
    summary: "Placeholder slot. Replace with a real identity and its problem.",
    image: "/media/work-03.png",
    scale: "standard",
  },
  {
    slug: "editorial-site",
    title: "Editorial Site",
    discipline: "Web design & development",
    year: "—",
    summary: "Placeholder slot. Replace with a real site and what it had to do.",
    image: "/media/work-04.png",
    scale: "standard",
  },
  {
    slug: "campaign",
    title: "Campaign",
    discipline: "Creative direction",
    year: "—",
    summary: "Placeholder slot. Replace with a real campaign end to end.",
    image: "/media/work-05.png",
    scale: "wide",
  },
];

export type AlbumImage = {
  id: string;
  src: string;
  alt: string;
  title: string;
  /** Shown in the popup. Replace with the real story behind the frame. */
  description: string;
  /** Placeholder slots below; swap for real edition details. */
  edition: string;
  /** Loose column placement and parallax depth. 1 = moves with the page. */
  column: "left" | "centre" | "right";
  depth: number;
  ratio: string;
};

export const album = {
  title: "Wings, and what they cost",
  standfirst:
    "A working set while the real albums are prepared. Scroll it as one piece \u2014 the frames are meant to arrive at different speeds, the way a room reveals itself.",
  /**
   * PLACEHOLDER IMAGERY. Generated by scripts/generate-placeholders.mjs, not
   * photographed. Titles and descriptions below are structural stand-ins; they
   * describe nothing real and must be replaced before launch.
   */
  images: [
    {
      id: "a1",
      src: "/media/album-01.png",
      alt: "Placeholder frame, vertical",
      title: "First light",
      description:
        "Placeholder. Replace with what was happening when this was taken, and why it stayed in the edit.",
      edition: "Print details to be confirmed",
      column: "left",
      depth: 0.82,
      ratio: "4 / 5",
    },
    {
      id: "a2",
      src: "/media/album-02.png",
      alt: "Placeholder frame, wide",
      title: "The long way round",
      description: "Placeholder. Replace with the real note for this frame.",
      edition: "Print details to be confirmed",
      column: "right",
      depth: 1.14,
      ratio: "16 / 9",
    },
    {
      id: "a3",
      src: "/media/album-03.png",
      alt: "Placeholder frame, square",
      title: "Held",
      description: "Placeholder. Replace with the real note for this frame.",
      edition: "Print details to be confirmed",
      column: "centre",
      depth: 0.9,
      ratio: "1 / 1",
    },
    {
      id: "a4",
      src: "/media/album-04.png",
      alt: "Placeholder frame, vertical",
      title: "Off the path",
      description: "Placeholder. Replace with the real note for this frame.",
      edition: "Print details to be confirmed",
      column: "right",
      depth: 0.76,
      ratio: "4 / 5",
    },
    {
      id: "a5",
      src: "/media/album-05.png",
      alt: "Placeholder frame, wide",
      title: "Last of the heat",
      description: "Placeholder. Replace with the real note for this frame.",
      edition: "Print details to be confirmed",
      column: "left",
      depth: 1.2,
      ratio: "16 / 9",
    },
    {
      id: "a6",
      src: "/media/album-06.png",
      alt: "Placeholder frame, vertical",
      title: "Quiet hour",
      description: "Placeholder. Replace with the real note for this frame.",
      edition: "Print details to be confirmed",
      column: "centre",
      depth: 0.94,
      ratio: "4 / 5",
    },
  ] satisfies AlbumImage[],
} as const;

export const services = [
  {
    title: "Photography",
    body: "Portrait, editorial, product and event. Shot with the final layout already in mind, so the crop you need exists.",
  },
  {
    title: "Videography",
    body: "Concept through grade. Short film, brand film, social cutdowns that were planned as cutdowns rather than salvaged into them.",
  },
  {
    title: "Brand & graphic design",
    body: "Identity, art direction and the unglamorous system underneath — type scale, grid, and rules that survive other people using them.",
  },
  {
    title: "Web design & development",
    body: "Design and build. Sites that load fast, read well on a phone, and do not collapse the moment real content arrives.",
  },
  {
    title: "Creative direction",
    body: "For teams who have the pieces and need someone to decide what they add up to, then hold that line through production.",
  },
] as const;

export const studio = {
  heading: "Running it as a business, not a hobby with a camera.",
  body: [
    "Working for yourself means the work has to survive contact with budgets, timelines and people who were not in the room when you had the idea. I would rather build that in from the start than protect an idea that cannot ship.",
    "That is the entrepreneurial part: owning the outcome, not just the deliverable.",
  ],
} as const;

export const process = [
  {
    title: "Interrogate",
    body: "What is this actually for, who decides it worked, and what is the honest constraint nobody has said out loud yet.",
  },
  {
    title: "Direct",
    body: "A single clear decision about what the thing is. Everything downstream is held against it.",
  },
  {
    title: "Produce",
    body: "Shoot, design, build. Fewer options, better executed, is a service — not a shortcut.",
  },
  {
    title: "Hand over",
    body: "Files organised, systems documented, and enough context that the work keeps working after I leave.",
  },
] as const;

export type ContactStep = {
  id: string;
  question: string;
  hint?: string;
  type: "text" | "email" | "longtext" | "choice";
  options?: readonly string[];
  optional?: boolean;
  /** Basic client-side validation message. */
  required_message?: string;
};

export const contactSteps: readonly ContactStep[] = [
  {
    id: "name",
    question: "First, what should I call you?",
    type: "text",
    required_message: "A name, so I know who I am replying to.",
  },
  {
    id: "email",
    question: "Where do I reach you?",
    hint: "I only use this to reply.",
    type: "email",
    required_message: "A valid email address, otherwise this goes nowhere.",
  },
  {
    id: "looking_for",
    question: "What are you looking for?",
    type: "choice",
    options: [
      "Photography",
      "Videography",
      "Brand & graphic design",
      "Web design & development",
      "Creative direction",
      "Not sure yet",
    ],
  },
  {
    id: "project_type",
    question: "And what kind of project is it?",
    type: "choice",
    options: [
      "Brand or campaign",
      "Editorial or personal",
      "Product or e-commerce",
      "Event",
      "Something else",
    ],
  },
  {
    id: "budget",
    question: "Roughly what budget are you working with?",
    hint: "An honest range saves us both a call.",
    type: "choice",
    options: [
      "Under £1k",
      "£1k – £5k",
      "£5k – £15k",
      "£15k+",
      "Rather discuss it",
    ],
  },
  {
    id: "brief",
    question: "Tell me about it.",
    hint: "What it is, who it is for, and what would make it a success.",
    type: "longtext",
    required_message: "Even two lines helps.",
  },
  {
    id: "timeline",
    question: "When does this need to happen?",
    type: "choice",
    options: ["Within weeks", "1 – 3 months", "3 months+", "No fixed date"],
  },
  {
    id: "extra",
    question: "Anything else I should know?",
    hint: "Optional. References, constraints, the thing you almost did not mention.",
    type: "longtext",
    optional: true,
  },
] as const;
